services: # No 'version:' line anymore
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_NAME: postgres
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 4318

  db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp" # UDP for Jaeger agent (Thrift)
      - "4318:4318"    # OTLP HTTP receiver (for OpenTelemetry SDKs, recommended)
      - "14268:14268"  # Jaeger Collector HTTP (for Thrift)
      - "16686:16686"  # Jaeger UI

  prometheus:
    image: prom/prometheus:latest
    ports:
     - "9090:9090"
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
     - "3000:3000"
    depends_on:
     - prometheus
    environment: # Corrected 'enviorment' typo
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
     - grafana-data:/var/lib/grafana # Referring to the named volume
    
volumes: # Top-level volumes section
  postgres-data:
  grafana-data: # <-- Explicitly defined the named volume here